name: wiseair_platform
description: The web platform by Wiseair

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^5.0.0 
  flutter_bloc: ^5.0.0
  equatable: ^1.2.0
  auto_size_text: ^2.1.0
  get_it: ^4.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

